version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      # Helper scripts
      - src: "envloader.sh"
        dst: "envloader.sh"
      - src: "envloader.ps1"
        dst: "envloader.ps1"
      - src: "envloader.cmd"
        dst: "envloader.cmd"
      # Wrapper scripts
      - src: "envload.sh"
        dst: "envload"
      - src: "envload.ps1"
        dst: "envload.ps1"
      - src: "envload.cmd"
        dst: "envload.cmd"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).